<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="6" total="8" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Test-Suite" duration-ms="64" started-at="2020-01-06T11:45:22Z" finished-at="2020-01-06T11:45:22Z">
    <groups>
      <group name="Smoke">
        <method signature="Carloan.nag_Carloan(java.lang.String)[pri:0, instance:com.wow.Carloan@675d3402]" name="nag_Carloan" class="com.wow.Carloan"/>
        <method signature="Mobileloan.Mobile_Loan_nag()[pri:0, instance:com.wow.Mobileloan@51565ec2]" name="Mobile_Loan_nag" class="com.wow.Mobileloan"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Group Test cases" duration-ms="64" started-at="2020-01-06T11:45:22Z" finished-at="2020-01-06T11:45:22Z">
      <class name="com.wow.Mobileloan">
        <test-method status="PASS" signature="Mobile_Loan_nag()[pri:0, instance:com.wow.Mobileloan@51565ec2]" name="Mobile_Loan_nag" duration-ms="2" started-at="2020-01-06T11:45:22Z" finished-at="2020-01-06T11:45:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Mobile_Loan_nag -->
      </class> <!-- com.wow.Mobileloan -->
      <class name="com.wow.Carloan">
        <test-method status="FAIL" signature="nag_Carloan(java.lang.String)[pri:0, instance:com.wow.Carloan@675d3402]" name="nag_Carloan" duration-ms="17" started-at="2020-01-06T11:45:22Z" finished-at="2020-01-06T11:45:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Santhosh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.wow.Carloan.nag_Carloan(Carloan.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nag_Carloan -->
      </class> <!-- com.wow.Carloan -->
    </test> <!-- Group Test cases -->
  </suite> <!-- Test-Suite -->
</testng-results>
